---
title: "Cluster_analysis"
output: html_document
date: "2025-06-10"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggstatsplot)
library(dndscv)
library(pheatmap)
library(factoextra)
library(cluster)
library(NbClust)
library(survival)
library(survminer)
library(ggsci)
library(readxl)
```

```{r load_data}
load("primary_data.RData")
load("all_patient_trajectories_cancer.RData")
df.clin<-read.table("tcga_clinicaldata.tsv",header=T,sep="\t")
```

```{r filter_data}
# All mean VAF calculated for each patient
all_patient_trajectories_cancer<-all_patient_trajectories_cancer %>% dplyr::rename("instability"=mutations)

# Calculate the number of zeros in each row
num_zeros <- apply(all_patient_trajectories_cancer, 1, function(row) sum(row == 0))

# Remove rows where 3 or more elements are zero
all_patient_trajectories_cancer_filt <- all_patient_trajectories_cancer[num_zeros < 2, ]

# Dont removre rows and keep all the data
all_patient_trajectories_cancer_RANK<-t(as.data.frame(apply(all_patient_trajectories_cancer,1,function(x) rank(-x, ties.method = "min"))))

all_patient_trajectories_cancer_RANK_filt<-t(as.data.frame(apply(all_patient_trajectories_cancer_filt,1,function(x) rank(-x, ties.method = "min"))))
```


```{r PCA biplot Fig 3A}
df.100<-as.data.frame(all_patient_trajectories_cancer_RANK_filt) %>% rownames_to_column("tcgaid")

## Get annotation to color
annotation_tmp <- df.clin %>% column_to_rownames("bcr_patient_barcode") %>% dplyr::select("type") %>% as.data.frame()
df.100.groupingvar<-annotation_tmp %>% rownames_to_column("tcgaid")
df.101 <- merge(df.100, df.100.groupingvar, by = "tcgaid", all.x = TRUE)
pca_result <- prcomp(df.101[, -c(1, ncol(df.101))], scale. = FALSE)

# Assuming pca_result is your PCA result and df.101 is your original data
biplot <- fviz_pca_biplot(pca_result, axes = c(1, 2), geom=c("point", "text"), 
                # Individuals
                geom.ind = "point",
                fill.ind = df.101$type, col.ind = "white",
                pointshape = 21, pointsize = 2,
                #palette = "jco",
                addEllipses = FALSE,
                # Variables
                alpha.var ="contrib", col.var = "black",
                gradient.cols = "RdBu"
                ) +
  labs(fill = "type", color = "Contrib", alpha = "Contrib") # Change legend title

# Calculate the center of each group
group_center <- df.101 %>%
  as.data.frame() %>%
  mutate(PC1 = pca_result$x[,1], PC2 = pca_result$x[,2]) %>%
  group_by(type) %>%
  summarise(center_PC1 = mean(PC1, na.rm = TRUE), center_PC2 = mean(PC2, na.rm = TRUE))

# Add group labels to the center of each group
plot_PCA1<-biplot + geom_text(data = group_center, aes(x = center_PC1, y = center_PC2, label = ""), size = 3, hjust = 1.2,)
```

```{r PCA plot red/blue Fig 3B}
# Extract the scores (coordinates) of the samples on the PCs
scores <- pca_result$x

# Perform k-means clustering
km_result <- kmeans(scores, centers=2)  

# change 'centers' to the number of clusters you want
##Test number of clusters
#nb <- NbClust(scores, distance = "euclidean", min.nc = 2,max.nc = 10, method = "kmeans")

# Now, km_result$cluster contains the cluster assignments for each sample
# You can add this to your original data frame
df.102 <- df.101
df.102$cluster <- as.character(km_result$cluster)

# Now you can plot again with the clusters
plot_PCA2<-fviz_pca_biplot(pca_result, axes = c(1, 2),geom=c("point", "text"), 
                # Individuals
                geom.ind = "point",repel = T,
                fill.ind = df.102$cluster, 
                shape.ind = df.102$cluster,  # Add this line to define shapes by cluster
                col.ind = "white",
                pointshape = 21, 
                pointsize = 2,
                #palette = "jco",
                addEllipses = FALSE,
                # Variables
                alpha.var ="contrib", 
                col.var = "black",
                gradient.cols = "RdBu"
                ) + labs(fill = "type", color = "Contrib", alpha = "Contrib") # Add shape to legend

```

```{r Proportion cluster cancer type Fig 3D}

df.clin_kmeans<-inner_join(df.clin,df.102,by = c("bcr_patient_barcode"="tcgaid")) 
# Create survival object
surv_obj <- Surv(time = df.clin_kmeans$OS.time, event = df.clin_kmeans$OS)

# Fit survival model
fit <- survfit(surv_obj ~ df.clin_kmeans$cluster)

# Plot survival model
psurv_rank2PCA_2Ks<-ggsurvplot(fit, data = df.clin_kmeans,risk.table = T, 
           pval = TRUE, # display p-value of log-rank test
           pval.method = TRUE,
           conf.int = TRUE, 
           risk.table.col = "strata", # change risk table color by groups
           linetype = "strata", # change line type by groups
           xlab = "Time in days", # Customize X-axis label
           ylab = "Survival probability", # Customize Y-axis label
           title = "Kaplan-Meier Survival Curve", # Add title
           legend = "bottom", # Change legend position
           ggtheme = theme_minimal(), # Add theme
           palette = "npg" # Add theme
          )


# Create a summary data frame
summary_df <- df.102 %>%
  group_by(type, cluster) %>%
  summarise(count = n(), .groups = 'drop') %>%
  mutate(proportion = count / sum(count))

# Create a bar plot
plot_bar_PCA_2Clusters<-ggplot(summary_df, aes(x = type, y = count, fill = cluster)) +
  geom_bar(stat = "identity", position = "dodge") + scale_fill_npg() +
  labs(x = "Tumor Type", y = "Count", fill = "Cluster") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```

```{r Survival by cluster Fig3C}

# Perform k-means clustering
#km_result <- kmeans(scores, centers=2,nstart = 50,iter.max = 250)  # change 'centers' to the number of clusters you want

# Now, km_result$cluster contains the cluster assignments for each sample
# You can add this to your original data frame
df.102 <- df.101
df.102$cluster <- as.character(km_result$cluster)

df.clin_kmeans<-inner_join(df.clin,df.102,by = c("bcr_patient_barcode"="tcgaid")) 
# Create survival object
surv_obj <- Surv(time = df.clin_kmeans$DFI.time, event = df.clin_kmeans$DFI)

# Fit survival model
fit <- survfit(surv_obj ~ df.clin_kmeans$cluster)

# Plot survival model
psurv_rank2PCA_2Ks_DFI<-ggsurvplot(fit, data = df.clin_kmeans,risk.table = F, 
           pval = TRUE, # display p-value of log-rank test
           pval.method = TRUE,
           #conf.int = TRUE, 
           #risk.table.col = "strata", # change risk table color by groups
           #linetype = "strata", # change line type by groups
           xlab = "Time in days", # Customize X-axis label
           #ylab = "Survival probability", # Customize Y-axis label
           title = "Disease Free", # Add title
           legend = "bottom", # Change legend position
           ggtheme = theme_minimal(), # Add theme
           palette = "npg" # Add theme
          )

surv_obj <- Surv(time = df.clin_kmeans$PFI.time, event = df.clin_kmeans$PFI)

# Fit survival model
fit <- survfit(surv_obj ~ df.clin_kmeans$cluster)

# Plot survival model
psurv_rank2PCA_2Ks_PFI<-ggsurvplot(fit, data = df.clin_kmeans,risk.table = F, 
           pval = TRUE, # display p-value of log-rank test
           pval.method = TRUE,
           #conf.int = TRUE, 
           #isk.table.col = "strata", # change risk table color by groups
           #linetype = "strata", # change line type by groups
           #xlab = "Time in days", # Customize X-axis label
           #ylab = "Survival probability", # Customize Y-axis label
           title = "Progression Free", # Add title
           legend = "bottom", # Change legend position
           ggtheme = theme_minimal(), # Add theme
           palette = "npg" # Add theme
          )
```
