---
title: "GTEx_analysis"
output: html_document
date: "2025-06-10"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggstatsplot)
library(ggeasy)
library(dndscv)
library(readxl)
library(ggvenn)
library(UpSetR)
library(ComplexHeatmap)
library(ggplot2)
library(dplyr)
library(readxl)
library(writexl)
library(ggupset)
library(readxl)
library(biomaRt)
library(RColorBrewer)
```

```{r load and prepare data}
load("//Relevant_analysis/Data/drivergenes.RData")
load("//Relevant_analysis/Data/list_names.RData")
load("//Relevant_analysis/Data/primary_data.RData")
load("//Relevant_analysis/Data/annotated_normal_data.RData")
load("//Relevant_analysis/Data/RefCDS_human_GRCh37_dNdScv.0.1.0.rda")
refdb_run =RefCDS
```


```{Pantissue VAF for normal tissues Fig 5A}
normal_plot<-annotated_normal_data%>%dplyr::filter(impact %in% c("Missense", "Nonsense","Essential_Splice","Stop_loss"))%>%dplyr::filter(gene %in% list_names$list_names)
#create 
df_angiogenesis<-normal_plot%>% filter(angiogenesis=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  angiogenesis)
df_angiogenesis$angiogenesis<-"angiogenesis"
colnames(df_angiogenesis)[colnames(df_angiogenesis) == 'angiogenesis'] <- 'category'

df_driver<-normal_plot%>% filter(driver=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  driver)
df_driver$driver<-"driver"
colnames(df_driver)[colnames(df_driver) == 'driver'] <- 'category'

df_escape<-normal_plot%>% filter(escape=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  escape)
df_escape$escape<-"escape"
colnames(df_escape)[colnames(df_escape) == 'escape'] <- 'category'

df_mutations<-normal_plot%>% filter(mutations=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  mutations)
df_mutations$mutations<-"genome instability"
colnames(df_mutations)[colnames(df_mutations) == 'mutations'] <- 'category'

df_growth<-normal_plot%>% filter(growth=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  growth)
df_growth$growth<-"growth"
colnames(df_growth)[colnames(df_growth) == 'growth'] <- 'category'

df_immortality<-normal_plot%>% filter(immortality=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  immortality)
df_immortality$immortality<-"immortality"
colnames(df_immortality)[colnames(df_immortality) == 'immortality'] <- 'category'

df_metastasis<-normal_plot%>% filter(metastasis=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  metastasis)
df_metastasis$metastasis<-"metastasis"
colnames(df_metastasis)[colnames(df_metastasis) == 'metastasis'] <- 'category'

df_inflammation<-normal_plot%>% filter(inflammation=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  inflammation)
df_inflammation$inflammation<-"inflammation"
colnames(df_inflammation)[colnames(df_inflammation) == 'inflammation'] <- 'category'

df_proliferation<-normal_plot%>% filter(proliferation=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  proliferation)
df_proliferation$proliferation<-"proliferation"
colnames(df_proliferation)[colnames(df_proliferation) == 'proliferation'] <- 'category'

df_death<-normal_plot%>% filter(death=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  death)
df_death$death<-"death"
colnames(df_death)[colnames(df_death) == 'death'] <- 'category'

df_metabolism<-normal_plot%>% filter(metabolism=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  metabolism)
df_metabolism$metabolism<-"metabolism"
colnames(df_metabolism)[colnames(df_metabolism) == 'metabolism'] <- 'category'

df_immune<-normal_plot%>% filter(immune=="YES")%>% dplyr::select(sampleID, gene, VAF, tissue,  immune)
df_immune$immune<-"immune evasion"
colnames(df_immune)[colnames(df_immune) == 'immune'] <- 'category'

df_density<-rbind(df_angiogenesis, df_metabolism, df_death, df_proliferation, df_inflammation, df_metastasis, df_immortality, df_growth, df_immune, df_mutations, df_driver, df_escape)

library("plotrix")
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      std.error = std.error(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

df_VAF<- data_summary(df_density, varname="VAF", 
                    groupnames= "category")
df_VAF<-df_VAF[-(3:4), ]
#plot VAF error bars
p1<-ggplot(df_VAF, aes(x= reorder(category, -VAF), y = VAF), color=category)+
  geom_errorbar(aes(ymin=VAF-std.error, ymax=VAF+std.error, color=category), width=0, position=position_dodge(0.78))+ rotate_x_text(45) +   
  geom_point(position = position_dodge(0.78), size = 1.5) +  cowplot::theme_cowplot()+theme(legend.position="none")+scale_y_log10()+ggtitle("Normal")+
  ggeasy::easy_center_title() +ylab("VAF") +xlab("Cancer hallmarks (ordered by VAF)")+ scale_color_manual(breaks = c("genome instability", "immortality", "metabolism", "angiogenesis","growth", "death","proliferation", "metastasis", "immune evasion", "inflammation"), values =c( "purple", "turquoise", "magenta", "red", "brown","blue","pink", "yellow", "orange", "green") )+theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ggtitle("Normal") +scale_y_continuous(breaks = seq(0.11, 0.13, by = 0.01), labels = c("0.11", "0.12", "0.13"), limits=c(0.11, 0.13))+ scale_x_discrete(limits = c("genome instability", "immortality","metabolism", "growth","angiogenesis","death","metastasis","proliferation","inflammation", "immune evasion"))
```


```{r load and prepare dnda analysis}
Gene_list_of_cancer_hallmarks <- read_excel("//Relevant_analysis/Data/Gene_list_of_cancer_hallmarks.xlsx")

#convert genes to ensembl id
library(biomaRt)
hsapiens_genes <- getBM(attributes = c("ensembl_gene_id", 
                                       "hgnc_symbol"),
                        mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl"))

all_hallmarks <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$ALL) 
all_hallmarks<-  unique(all_hallmarks$hgnc_symbol)
all_hallmarks<-as.data.frame(all_hallmarks)

angiogenesis <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$ANGIOGENESIS) 
angiogenesis<-  unique(angiogenesis$hgnc_symbol)
angiogenesis<-as.data.frame(angiogenesis)
angiogenesis<-angiogenesis%>%filter(angiogenesis %in% list_names$list_names)


metabolism <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$METABOLISM) 
metabolism<-  unique(metabolism$hgnc_symbol)
metabolism<-as.data.frame(metabolism)


death <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$DEATH) 
death<-  unique(death$hgnc_symbol)
death<-as.data.frame(death)

proliferation <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$PROLIFERATION) 
proliferation<-  unique(proliferation$hgnc_symbol)
proliferation<-as.data.frame(proliferation)


inflammation <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$INFLAMMATION) 
inflammation<-  unique(inflammation$hgnc_symbol)
inflammation<-as.data.frame(inflammation)

metastasis <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$METASTASIS) 
metastasis<-  unique(metastasis$hgnc_symbol)
metastasis<-as.data.frame(metastasis)

immortality <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$IMMORTALITY) 
immortality<-  unique(immortality$hgnc_symbol)
immortality<-as.data.frame(immortality)


growth <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$GROWTH) 
growth<-  unique(growth$hgnc_symbol)
growth<-as.data.frame(growth)


immune <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$IMMUNE) 
immune<-  unique(immune$hgnc_symbol)
immune<-as.data.frame(immune)

mutations <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% Gene_list_of_cancer_hallmarks$MUTATIONS) 
mutations<-  unique(mutations$hgnc_symbol)
mutations<-as.data.frame(mutations)


escape_genes = readxl::read_xlsx("/Users/luciegourmet/Dropbox/Projects/DriverLandscape/Data/SuppTable3_escapegenes_Aug2021.xlsx")
colnames(escape_genes)<-"escape"

#filter
death<-death%>%filter(death %in% list_names$list_names)
driver<-drivergenes%>%filter(drivergenes %in% list_names$list_names)
escape<-escape_genes%>%filter(escape %in% list_names$list_names)
growth<-growth%>%filter(growth %in% list_names$list_names)
immune<-immune%>%filter(immune %in% list_names$list_names)
immortality<-immortality%>%filter(immortality %in% list_names$list_names)
inflammation<-inflammation%>%filter(inflammation %in% list_names$list_names)
metabolism<-metabolism%>%filter(metabolism %in% list_names$list_names)
metastasis<-metastasis%>%filter(metastasis %in% list_names$list_names)
mutations<-mutations%>%filter(mutations %in% list_names$list_names)
proliferation<-proliferation%>%filter(proliferation %in% list_names$list_names)
angiogenesis<-angiogenesis%>%filter(angiogenesis %in% list_names$list_names)
```


```{r run dnds on each gene list of hallmarks}
df_normal_angiogenesis_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =angiogenesis$angiogenesis)
df_normal_metabolism_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =metabolism$metabolism)
df_normal_death_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =death$death)
df_normal_proliferation_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =proliferation$proliferation)
df_normal_inflammation_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =inflammation$inflammation)
df_normal_metastasis_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL,gene_list =metastasis$metastasis)
df_normal_immortality_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =immortality$immortality)
df_normal_growth_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =growth$growth)
df_normal_immune_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =immune$immune)
df_normal_mutations_dndscv<-dndscv(annotated_normal_data, refdb = refdb_run ,cv=NULL, gene_list =mutations$mutations)
```


```{r plot dnds for hallmarks Fig 6A}
plotdnds<-function(x){
  df_1<-x$globaldnds
  Globaldnds<- c(df_1[1,2])
  dndshigh<- c(df_1[1,4])
  dndslow<- c(df_1[1,3])
  df_x <- data.frame(Globaldnds, dndshigh, dndslow)
  return(df_x)
}
#get the mean and confidence interval for each hallmark
p_angiogenesis<-plotdnds(x =df_normal_angiogenesis_dndscv)
p_angiogenesis$Hallmark<-"angiogenesis"

p_mutations<-plotdnds(x =df_normal_mutations_dndscv)
p_mutations$Hallmark<-"genome instability"

p_immune<-plotdnds(x =df_normal_immune_dndscv)
p_immune$Hallmark<-"immune evasion"

p_growth<-plotdnds(x =df_normal_growth_dndscv)
p_growth$Hallmark<-"growth"

p_immortality<-plotdnds(x =df_normal_immortality_dndscv)
p_immortality$Hallmark<-"immortality"

p_metastasis<-plotdnds(x =df_normal_metastasis_dndscv)
p_metastasis$Hallmark<-"metastasis"

p_inflammation<-plotdnds(x =df_normal_inflammation_dndscv)
p_inflammation$Hallmark<-"inflammation"

p_proliferation<-plotdnds(x =df_normal_proliferation_dndscv)
p_proliferation$Hallmark<-"proliferation"

p_death<-plotdnds(x =df_normal_death_dndscv)
p_death$Hallmark<-"death"

p_metabolism<-plotdnds(x =df_normal_metabolism_dndscv)
p_metabolism$Hallmark<-"metabolism"

p_driver<-plotdnds(x =df_normal_driver_dndscv)
p_driver$Hallmark<-"driver"

p_escape<-plotdnds(x =df_normal_escape_dndscv)
p_escape$Hallmark<-"escape"

#only plot the 10 hallmarks
p_hallmarks<-rbind(p_metabolism, p_death, p_proliferation, p_inflammation, p_metastasis, p_immortality, p_growth, p_immune, p_mutations, p_angiogenesis)

Pancancer<-ggplot(p_hallmarks, aes(x= reorder(Hallmark, -Globaldnds), y = Globaldnds), color=Hallmark)+
  geom_errorbar(aes(ymin=dndslow, ymax=dndshigh, color=Hallmark), width=0, position=position_dodge(0.78))+ rotate_x_text(45) +   
  geom_point(position = position_dodge(0.78), size = 1.5) +  cowplot::theme_cowplot()+ geom_hline(yintercept=1, linetype="dashed", color = "red")+theme(legend.position="none")+scale_y_log10()+xlab("Cancer hallmarks (ordered by dN/dS)") +ylab("dN/dS") +ggtitle("Normal")+
  ggeasy::easy_center_title() + scale_color_manual(breaks = c("genome instability", "immortality", "metabolism", "angiogenesis","growth", "death","proliferation", "metastasis", "immune", "inflammation"), values =c("purple", "turquoise", "magenta", "red", "brown","blue","pink", "yellow", "orange", "green") )+
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ scale_x_discrete(limits = c("immortality","genome instability","metabolism","angiogenesis","growth","immune evasion","death","inflammation","proliferation", "metastasis"))
```

---
"upset_plot_hallmarks"

---



```{r prepare data and plot Fig 1C}
#reading the data
load("drivergenes.RData")
#stratify patients depending on whether they have hallmark mutations
Gene_list_of_cancer_hallmarks <- read_excel("Gene_list_of_cancer_hallmarks.xlsx")
load("list_names.RData")

hallmark_genes<-Gene_list_of_cancer_hallmarks %>% unique()
#convert genes to ensembl id
hsapiens_genes <- getBM(attributes = c("ensembl_gene_id", 
                                       "hgnc_symbol"),
                        mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl"))

all_hallmarks <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$ALL)
all_hallmarks<-  unique(all_hallmarks$hgnc_symbol)
all_hallmarks<-as.data.frame(all_hallmarks)

angiogenesis <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$ANGIOGENESIS) 
angiogenesis<-  unique(angiogenesis$hgnc_symbol)
angiogenesis<-as.data.frame(angiogenesis)
angiogenesis<-angiogenesis%>%filter(angiogenesis %in% list_names$list_names)


metabolism <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$METABOLISM) 
metabolism<-  unique(metabolism$hgnc_symbol)
metabolism<-as.data.frame(metabolism)

death <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$DEATH) 
death<-  unique(death$hgnc_symbol)
death<-as.data.frame(death)

proliferation <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$PROLIFERATION) 
proliferation<-  unique(proliferation$hgnc_symbol)
proliferation<-as.data.frame(proliferation)

inflammation <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$INFLAMMATION) 
inflammation<-  unique(inflammation$hgnc_symbol)
inflammation<-as.data.frame(inflammation)

metastasis <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$METASTASIS) 
metastasis<-  unique(metastasis$hgnc_symbol)
metastasis<-as.data.frame(metastasis)

immortality <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$IMMORTALITY) 
immortality<-  unique(immortality$hgnc_symbol)
immortality<-as.data.frame(immortality)


growth <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$GROWTH) 
growth<-  unique(growth$hgnc_symbol)
growth<-as.data.frame(growth)


immune <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$IMMUNE) 
immune<-  unique(immune$hgnc_symbol)
immune<-as.data.frame(immune)

mutations <- hsapiens_genes %>%filter(hsapiens_genes$hgnc_symbol %in% hallmark_genes$MUTATIONS) 
mutations<-  unique(mutations$hgnc_symbol)
mutations<-as.data.frame(mutations)

escape_genes = readxl::read_xlsx("SuppTable3_escapegenes_Aug2021.xlsx")
colnames(escape_genes)<-"escape"

#filter
death<-death%>%filter(death %in% list_names$list_names)
driver<-drivergenes%>%filter(drivergenes %in% list_names$list_names)
escape<-escape_genes%>%filter(escape %in% list_names$list_names)
growth<-growth%>%filter(growth %in% list_names$list_names)
immune<-immune%>%filter(immune %in% list_names$list_names)
immortality<-immortality%>%filter(immortality %in% list_names$list_names)
inflammation<-inflammation%>%filter(inflammation %in% list_names$list_names)
metabolism<-metabolism%>%filter(metabolism %in% list_names$list_names)
metastasis<-metastasis%>%filter(metastasis %in% list_names$list_names)
mutations<-mutations%>%filter(mutations %in% list_names$list_names)
proliferation<-proliferation%>%filter(proliferation %in% list_names$list_names)
angiogenesis<-angiogenesis%>%filter(angiogenesis %in% list_names$list_names)

myGeneSets <- list(
  angiogenesis= angiogenesis$angiogenesis,
  metabolism = metabolism$metabolism,
  death  = death$death,
  proliferation= proliferation$proliferation,
  inflammation=inflammation$inflammation,
  metastasis=metastasis$metastasis,
  immortality=immortality$immortality,
  growth=growth$growth,
  immune_evasion=immune$immune,
  genome_instability=mutations$mutations,
  driver= driver$driver,
  escape=escape_genes$escape
)



pal=c( "red", "blue", "turquoise", "green", "brown", "black","yellow","orange","magenta", "pink", "purple", "grey")
mycolors <- colorRampPalette(pal)(232)

p<-upset(fromList(myGeneSets), nsets = 12, main.bar.color=mycolors, sets.bar.color=c( "red", "blue", "turquoise", "green", "brown", "black","yellow","orange","magenta", "pink", "purple", "grey"))
```
